### ISSUE TITLE
determineLocale failed when running gulp task.

### ISSUE THREAD

**Issue by PJWEBRob** [perrin4869/gulp-i18next-conv#65]
I get the following error when I try to run gulp build-locale

    Starting 'locale-build'...
    Unhandled rejection Error in plugin 'gulp-i18next-conv'
    Message:
    determineLocale failed

The code inside my gulp task is the same as the example provided:

```
gulp.task('locale-build', function() {
  // Backend locales
  return gulp.src('locale/*/LC_MESSAGES/*.po')
  .pipe(i18next())
  .pipe(jsonminify())
  .pipe(rename(path => path.dirname = path.dirname.replace('/LC_MESSAGES', '')))
  .pipe(gulp.dest('locale'));
});
```

My directory structure is as follows:
`locale/en_GB/LC_MESSAGES/en_GB.po`
`locale/fr_FR/LC_MESSAGES/fr_FR.po`

Could this potentially be the issue?

**Comment by PJWEBRob** [comment]
@perrin4869, After reading through #64 retrospectively, it seems I am having a similar issue as described in later comments.

I attempted the debug you mentioned with similar results:
```
determineLocale(filepath => {
                                      ^^

SyntaxError: Unexpected token =>
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Liftoff.handleArguments
```

**Comment by PJWEBRob** [comment]
I have deployed the same code to a test server (running Linux) it works fine. So this is defiantly an issue with the windows filesystem. I do remember having issues with Locales using PHP Gettext on windows.

Not sure how this can be fixed/patched.

**Comment by perrin4869** [comment]
Hi thanks for the issue report!
I actually spend 99% of my development time on a Linux machine, so I can't
really support Windows without your help. Any chance you can help me debug
this?

**Comment by PJWEBRob** [comment]
Hi, I'd be happy to help you. Just let me know what you need me to do!

**Comment by PJWEBRob** [comment]
I found the issue and have fixed it locally.

determineLocale is expecting a filename using forwardslashes like so: `en_GB/LC_MESSAGES/en_GB.po`

However, windows passes the filename as `en_GB\LC_MESSAGES\en_GB.po` which means `match()` never actually matches anything

If you run a `replace(/\\/g,"/")` on the filename before doing the `match()` it works a treat on both windows and linux.

This fix will also resolve #64.

**Comment by perrin4869** [comment]
Can you check if `3.0.1` fixes this issue for you?

**Comment by PJWEBRob** [comment]
I will be able to check today, I will let you know once I have tested it :)

**Comment by PJWEBRob** [comment]
Your latest npm package only seems to contain 3 files:
- LICENSE.md
- package.json
- README.md

**Comment by perrin4869** [comment]
Damn, sorry, seems travis ci failed to deploy properly =/
Fixed in `4.0.1`

**Comment by PJWEBRob** [comment]
Thank you, this works perfectly! 🥇

**Comment by PJWEBRob** [comment]
Issue now resolved.
